### ISSUE TITLE
Pinching to zoom the map doesn't work on avatars

### ISSUE THREAD

**Issue by louisdh** [wwdc-family/app#37]
Avatars seem to block the pinch gesture recognizer.

**Comment by KrauseFx** [comment]
Thanks for reporting this. Yeah, it's a shame, but that's how the map view on  maps in react native works... I'll try to switch to Google Maps, but it's not easy to get it to run.

**Comment by KrauseFx** [comment]
Should be fixed with Google maps, pushing the change soon 👍
