### ISSUE TITLE
[Optional] Setup OTA update system that gets generated by Travis for each commit

### ISSUE THREAD

**Issue by KrauseFx** [wwdc-family/app#9]
There is some services out there, haven't had time to decide which one to use

**Comment by orta** [comment]
We used https://apphub.io 

https://github.com/artsy/emission/blob/master/.travis.yml#L11
https://github.com/artsy/emission/blob/master/scripts/deploy_apphub.sh

PR looks like https://github.com/artsy/emission/pull/263

**Comment by KrauseFx** [comment]
Working on this now
